### ISSUE TITLE
Diaspora Federation Showing Hubzilla Nodes US Diaspora

### ISSUE THREAD

**Issue by royalterra** [jaywink/diaspora-hub#36]
if I visit the URL  http://the-federation.info/  I can see my Node blablanet.com  but say is Diaspora when the true is Hubzilla . Also I notice all the Hubzilla nodes have disapear and only showing some Redmatrix

![diaspora](https://cloud.githubusercontent.com/assets/8831558/11020972/cea1a71a-8629-11e5-92d6-0608dd871563.png)

**Comment by jaywink** [comment]
Thanks for the report. Yeah, have lacked time to update the site since a while. Anything it doesn't recognize (ie Hubzilla) is assumed as being diaspora* at the moment due to when the site was created only some pods had the network name available.

Will try to fix as soon as time, PR's welcome in the mean time :)

**Comment by jaywink** [comment]
Fixed by #37 !
